/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Unifyair Docs",
  "favicon": "img/favicon.png",
  "url": "https://google.com",
  "baseUrl": "/",
  "organizationName": "unifyair",
  "projectName": "docs",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "routeBasePath": "/",
          "sidebarPath": "./sidebars.ts",
          "remarkPlugins": [
            null
          ],
          "rehypePlugins": [
            null
          ]
        },
        "theme": {
          "customCss": [
            "./src/css/custom.css",
            "./src/css/rust-prismtheme.css"
          ]
        }
      }
    ]
  ],
  "themeConfig": {
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "title": "",
      "logo": {
        "alt": "Unfiyair Docs",
        "src": "img/logo.svg",
        "href": "https://unifyair.com",
        "className": "unifyair-logo"
      },
      "items": [
        {
          "href": "https://unifyair.com/",
          "label": "Home",
          "position": "right",
          "className": "navbar-center nav-link-same-page"
        },
        {
          "href": "https://unifyair.com/about",
          "label": "About",
          "position": "right",
          "className": "navbar-center nav-link-same-page"
        },
        {
          "to": "/",
          "label": "Docs",
          "position": "right",
          "className": "navbar-center nav-link-same-page"
        },
        {
          "href": "https://unifyair.com/contact",
          "label": "Contact",
          "position": "right",
          "className": "navbar-center nav-link-same-page"
        },
        {
          "href": "https://discord.gg/yuJHdZ4vEF",
          "aria-label": "Discord",
          "position": "right",
          "className": "navbar-discord-link navbar-image-link"
        },
        {
          "href": "https://github.com/unifyair",
          "aria-label": "GitHub repository",
          "position": "right",
          "className": "navbar-github-link navbar-image-link"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Tutorial",
              "to": "/docs/intro"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Stack Overflow",
              "href": "https://stackoverflow.com/questions/tagged/docusaurus"
            },
            {
              "label": "Discord",
              "href": "https://discordapp.com/invite/docusaurus"
            },
            {
              "label": "X",
              "href": "https://x.com/docusaurus"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Blog",
              "to": "/blog"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/unifyair"
            }
          ]
        }
      ]
    },
    "prism": {
      "defaultLanguage": "bash",
      "additionalLanguages": [
        "cpp",
        "bash",
        "json",
        "java",
        "rust"
      ],
      "theme": {
        "plain": {},
        "styles": []
      },
      "darkTheme": {
        "plain": {},
        "styles": []
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    },
    "liveCodeBlock": {
      "playgroundPosition": "bottom"
    }
  },
  "clientModules": [
    "/Users/pranavkumar/Desktop/blocknet/docs-website/custom-events/navbar-opacity.js",
    "/Users/pranavkumar/Desktop/blocknet/docs-website/custom-events/navbar-div-grouping.js"
  ],
  "themes": [
    "@docusaurus/theme-mermaid",
    "@docusaurus/theme-live-codeblock",
    [
      "/Users/pranavkumar/Desktop/blocknet/docs-website/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js",
      {
        "hashed": true,
        "language": [
          "en",
          "zh"
        ],
        "highlightSearchTermsOnTargetPage": true,
        "explicitSearchResultPath": true
      }
    ]
  ],
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "stylesheets": [
    "https://cdn.jsdelivr.net/npm/prism-themes@1.9.0/themes/prism-vsc-dark-plus.min.css",
    {
      "href": "https://cdn.jsdelivr.net/npm/katex@0.13.24/dist/katex.min.css",
      "type": "text/css",
      "integrity": "sha384-odtC+0UGzzFL/6PNoE8rX/SPcQDXBJ+uRepguP4QkPCm2LBxH3FA3y+fKSiJ+AmM",
      "crossorigin": "anonymous"
    }
  ],
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "scripts": [],
  "headTags": [],
  "tagline": "",
  "titleDelimiter": "|",
  "noIndex": false
};
